#docker compose base file

networks:
  public_net:
  dmz_net:
  service_mesh:
  logging_net:

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

services:
  #WAF SERVICE
  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./infra/waf/modsecurity.conf:/etc/nginx/modsecurity.conf:rw
    networks:
      - public_net
      - dmz_net
      - logging_net
    depends_on:
      - vault
    # API GATEWAY SERVICE
  # api_gateway:
  #   build:
  #     context: .
  #     dockerfile: ops/docker/backend.Dockerfile
  #   networks:
  #     - dmz_net
  #     - service_mesh
  #     - logging_net
  #   environment:
  #     - VAULT_ADDR=http://vault:8200
  #   depends_on:
  #     - vault
  #     - logstash
    # VAULT SERVICE
  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    networks:
      - service_mesh
      - logging_net
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - "monitoring"
    restart: no
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infra/monitoring/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - logging_net
    depends_on:
      - alertmanager

  # Alertmanager - Gestion et envoi des alertes vers Discord
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    profiles:
      - "monitoring"
    restart: no
    depends_on:
      - vault
    volumes:
      - ./infra/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./infra/monitoring/alertmanager/entrypoint.sh:/entrypoint.sh
      - alertmanager_data:/alertmanager
    entrypoint: /entrypoint.sh
    environment:
      # Webhook Discord stockÃ© dans Vault (secret/data/alertmanager)
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root_token_dev_only
    ports:
      - "9093:9093"
    networks:
      - logging_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # On utilise profile en tant que "interupteur" pour eviter qu'il consomme de la memoire pr rien. 
    # Avec cette ligne, grafana ne demarrera que si je tape [docker compose --profile monitoring up] sino  eteint par default
    profiles:
      - "monitoring"
    user: "472"
    depends_on:
      - prometheus
      - vault
    # http://localhost:3000 -> voir les graphiques sur le navigateur
    ports:
      - 3000:3000
    volumes:
      # l1: persisitane, si power off alors comptes utilisateurs et dashboards sauvegardes 
      #l2: script d'automatisation qui evite de configurer garafana a prometheus a la main
      - grafana_data:/var/lib/grafana
      - ./infra/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/monitoring/grafana/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    environment:
      - GF_SECURITY_ADMIN_USER=grafana_admin
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root_token_dev_only
    networks:
      - logging_net
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    profiles:
      - "monitoring"
    privileged:
      true
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - logging_net
