#docker compose base file

networks:
  public_net:
  dmz_net:
  service_mesh:
  logging_net:

# Persistent volumes
volumes:
  postgres_data:
  redis_data:

services:
  #WAF SERVICE
  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./infra/waf/modsecurity.conf:/etc/nginx/modsecurity.conf:rw
    networks:
      - public_net
      - dmz_net
      - logging_net
    depends_on:
      - vault
    # API GATEWAY SERVICE
  # api_gateway:
  #   build:
  #     context: .
  #     dockerfile: ops/docker/backend.Dockerfile
  #   networks:
  #     - dmz_net
  #     - service_mesh
  #     - logging_net
  #   environment:
  #     - VAULT_ADDR=http://vault:8200
  #   depends_on:
  #     - vault
  #     - logstash
    # VAULT SERVICE
  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    networks:
      - service_mesh

  # DATABASE SERVICE
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root_admin
    volumes:
      - postgres_data:/var/lib/postgres/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - service_mesh
      - logging_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root_admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - vault

  # REDIS SERVICE
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - service_mesh
      - logging_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - vault

